#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap           3 #normally 12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config -m LVDS1 top_padding 28
bspc config -m VGA1 top_padding 23

bspc monitor LVDS1 -d I III V  
bspc monitor VGA1 -d II IV VI

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center /home/derek/wallpaper.jpg &

$HOME/.config/polybar/launch.sh
